import {
  Authentication,
  Dashboard,
  PlantList,
  User,
  FarmPicker,
  ForgetPassword,
  Landing,
  OTP,
  PlantDetails,
  Weather,
  ResetPassword,
  FarmInfo,
  ProcessList,
  ProcessDetails,
  PlanList,
  PlanDetail,
  Worklog,
  WorklogDetail,
  AddPlan,
  UpdatePlan,
  CreateFarm,
  LandPlot,
  LandPlotCreate,
  PackageList,
  MasterType,
  GrowthStage,
  LandRow,
  EmployeeList,
  PackagePurchase,
  PaymentConfirmation,
  PaymentSuccess,
  PaymentCancel,
  PlantLot,
  Partner,
  EmployeeWorklog,
  EmployeeWorklogDetail,
  PlantLotDetails,
} from "@/pages";
import {
  EmployeeLayout,
  EmptyLayout,
  FarmPickerLayout,
  GuestLayout,
  ManagementLayout,
  PaymentLayout,
} from "@/layouts";
import { PATHS } from "./Paths";
import EmployeeDashboard from "@/pages/EmployeeView/EmployeeDashboard/EmployeeDashboard";

interface RouteItem {
  path: string;
  component: () => JSX.Element | undefined;
  layout?: React.ComponentType<any> | null;
  props?: Record<string, any>;
}

export const publicRoutes: RouteItem[] = [
  { path: PATHS.AUTH.LANDING, component: Landing, layout: GuestLayout },
  { path: PATHS.FARM_PICKER, component: FarmPicker, layout: FarmPickerLayout },
  { path: PATHS.FARM.CREATE_FARM, component: CreateFarm, layout: FarmPickerLayout },
  { path: PATHS.AUTH.LOGIN, component: Authentication, layout: EmptyLayout },
  { path: PATHS.AUTH.FORGOT_PASSWORD, component: ForgetPassword, layout: EmptyLayout },
  { path: PATHS.PACKAGE.PACKAGE_PURCHASE, component: PackagePurchase, layout: PaymentLayout },
  {
    path: `${PATHS.PACKAGE.PAYMENT}/:packageId`,
    component: PaymentConfirmation,
    layout: PaymentLayout,
  },
  { path: `${PATHS.PACKAGE.SUCCESS}`, component: PaymentSuccess, layout: PaymentLayout },
  { path: `${PATHS.PACKAGE.CANCEL}`, component: PaymentCancel, layout: PaymentLayout },
  {
    path: PATHS.AUTH.FORGOT_PASSWORD_OTP,
    component: OTP,
    layout: EmptyLayout,
    props: { type: "reset" },
  },
  {
    path: PATHS.AUTH.FORGOT_PASSWORD_RESET,
    component: ResetPassword,
    layout: EmptyLayout,
  },
  { path: PATHS.AUTH.SIGN_UP_OTP, component: OTP, layout: EmptyLayout, props: { type: "sign-up" } },
  { path: PATHS.EMPLOYEE.DASHBOARD, component: EmployeeDashboard, layout: EmployeeLayout },
  { path: PATHS.EMPLOYEE.WORK_SCHEDULE, component: EmployeeWorklog, layout: EmployeeLayout },
  { path: PATHS.EMPLOYEE.WORKLOG_DETAIL, component: EmployeeWorklogDetail, layout: EmployeeLayout },
  { path: PATHS.EMPLOYEE.WORKLOG, component: EmployeeDashboard, layout: EmployeeLayout },
  { path: PATHS.EMPLOYEE.PLANTS, component: EmployeeDashboard, layout: EmployeeLayout },
  { path: PATHS.EMPLOYEE.AI_CONSULTING, component: EmployeeDashboard, layout: EmployeeLayout },
  { path: PATHS.DASHBOARD, component: Dashboard, layout: ManagementLayout },
  { path: PATHS.USER.USER_LIST, component: User, layout: ManagementLayout },
  { path: PATHS.CLASSIFICATION.MASTER_TYPE, component: MasterType, layout: ManagementLayout },
  { path: PATHS.CLASSIFICATION.GROWTH_STAGE, component: GrowthStage, layout: ManagementLayout },
  { path: PATHS.FARM.FARM_INFO, component: FarmInfo, layout: ManagementLayout },
  { path: PATHS.FARM.FARM_PLANT_LIST, component: PlantList, layout: ManagementLayout },
  { path: PATHS.FARM.FARM_PLANT_DETAIL, component: PlantDetails, layout: ManagementLayout },
  { path: PATHS.FARM.FARM_PLOT_LIST, component: LandPlot, layout: ManagementLayout },
  { path: PATHS.FARM.FARM_ROW_LIST, component: LandRow, layout: ManagementLayout },
  {
    path: PATHS.FARM.FARM_PLANT_DETAIL_FROM_ROW,
    component: PlantDetails,
    layout: ManagementLayout,
  },
  { path: PATHS.FARM.FARM_PLANT_LOT_LIST, component: PlantLot, layout: ManagementLayout },
  { path: PATHS.FARM.FARM_PLANT_LOT_DETAIL, component: PlantLotDetails, layout: ManagementLayout },
  {
    path: PATHS.FARM.FARM_PLANT_LOT_ADDITIONAL,
    component: PlantLotDetails,
    layout: ManagementLayout,
  },
  { path: PATHS.WEATHER.WEATHER, component: Weather, layout: ManagementLayout },
  { path: PATHS.PROCESS.PROCESS_LIST, component: ProcessList, layout: ManagementLayout },
  { path: PATHS.PROCESS.PROCESS_DETAIL, component: ProcessDetails, layout: ManagementLayout },
  { path: PATHS.PLAN.PLAN_LIST, component: PlanList, layout: ManagementLayout },
  { path: PATHS.PLAN.PLAN_DETAIL, component: PlanDetail, layout: ManagementLayout },
  { path: PATHS.PLAN.ADD_PLAN, component: AddPlan, layout: ManagementLayout },
  { path: PATHS.PLAN.UPDATE_PLAN, component: UpdatePlan, layout: ManagementLayout },
  { path: PATHS.HR.WORKLOG_CALENDAR, component: Worklog, layout: ManagementLayout },
  { path: PATHS.HR.WORKLOG_DETAIL, component: WorklogDetail, layout: ManagementLayout },
  { path: PATHS.HR.EMPLOYEES, component: EmployeeList, layout: ManagementLayout },
  { path: PATHS.PARTNERS.PARTNER_LIST, component: Partner, layout: ManagementLayout },
  { path: PATHS.PACKAGE.PACKAGE_LIST, component: PackageList, layout: ManagementLayout },
];

export const privateRoutes: RouteItem[] = [];
