export interface GetPlan {
  planId: string;
  planName: string;
  status: string;
  planCode: string;
  createDate: Date;
  startDate: Date;
  endDate: Date;
  startTime: Date;
  endTime: Date;
  updateDate: Date;
  isActive: boolean;
  notes: string;
  planDetail: string;
  responsibleBy: string[];
  frequency: string;
  landPlot: number;
  assignorId: string;
  pesticideName: string;
  maxVolume: number;
  minVolume: number;
  processId: string;
  cropId: string;
  growthStageId: string;
  isDelete: boolean;
  masterTypeId: string;
  farmId: string;
  daysOfWeek: number[];
  daysOfMonth: number[];
  customDates : Date[];
}
