name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: CapstoneProjectSP25IPASAPI20250519223152
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
          
      - name: Restore
        run: dotnet restore BE/CapstoneProject_SP25_IPAS/CapstoneProject_SP25_IPAS.sln
        
      - name: Build
        run: dotnet build BE/CapstoneProject_SP25_IPAS/CapstoneProject_SP25_IPAS.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish BE/CapstoneProject_SP25_IPAS/CapstoneProject_SP25_IPAS.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
